name: .NET

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:

    build:

        strategy:
            matrix:
                configuration: [ Debug, Release ]

        runs-on: windows-latest  # For a list of available runner types, refer to https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

        env:
            Solution: src/WpfMessageBox.sln
            Configuration: ${{ matrix.configuration }}

        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   name: Install .NET Core
                uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: 9.0.x

            -   name: Display dotnet version
                run: dotnet --version

            -   name: Restore nugets
                run: dotnet restore $env:Solution

            -   name: Build
                run: dotnet build --no-restore --configuration $env:Configuration $env:Solution
